version: '3.8'

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 8501:8501
    networks:
      - fullstack-network
    restart: on-failure

  backend:
    build: backend
    platform: linux/amd64
    container_name: backend
    ports:
      - 8083:8083
    networks:
      - fullstack-network
    restart: on-failure

networks:
  fullstack-network:
    driver: bridge