apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-app
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
      - name: frontend
        image: your-registry/frontend:latest
        ports:
        - containerPort: 8501
      - name: backend
        image: your-registry/backend:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-app-service
spec:
  type: LoadBalancer
  ports:
  - name: frontend
    port: 8501
    targetPort: 8501
  - name: backend
    port: 8083
    targetPort: 8083
  selector:
    app: fullstack-app
