name: Deploy Frontend Docker image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push the Frontend Docker image to ECR registry
      # You may pin to the exact commit or the version.
      # uses: kciter/aws-ecr-action@ea6db9ecebec495c996b0f084c8ea1591f1185d7
      uses: kciter/aws-ecr-action@ea6db9ecebec495c996b0f084c8ea1591f1185d7
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Account ID
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        # A comma-delimited list of AWS account IDs that are associated with the ECR registries. If you do not specify a registry, the default ECR registry is assumed
        registry_ids: ${{ secrets.FRONTEND_IMAGE_ECR }}
        # A role to assume under the account_id account.
        # Name of your ECR repository
        repo: frontend_image
        # The AWS region
        region: "us-east-2" 
        # Set this to true to create the repository if it does not already exist
        create_repo: false
        # Set this to true to set a policy on the repository
        set_repo_policy: false
        # Name of Dockerfile to use
        dockerfile: Dockerfile
        # Path to Dockerfile, defaults to the working directory
        path: frontend
          
